version: "3.1"

volumes:
  postgresql_data:

services:
  postgresql:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medods
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgresql_medods
