// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	dto "auth_service/internal/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateUserSession provides a mock function with given fields: ctx, req
func (_m *Repository) CreateUserSession(ctx context.Context, req dto.UserSessionRepoCreate) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserSessionRepoCreate) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserSession provides a mock function with given fields: ctx, guid, _a2
func (_m *Repository) GetUserSession(ctx context.Context, guid string, _a2 time.Time) (dto.UserSessionRepoGet, error) {
	ret := _m.Called(ctx, guid, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSession")
	}

	var r0 dto.UserSessionRepoGet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (dto.UserSessionRepoGet, error)); ok {
		return rf(ctx, guid, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) dto.UserSessionRepoGet); ok {
		r0 = rf(ctx, guid, _a2)
	} else {
		r0 = ret.Get(0).(dto.UserSessionRepoGet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, guid, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
